export const QUERY_KEYS = {
  USER: 'user',
  MY_ACCOUNT: 'my-account',
  MY_ACCOUNT_LIST: 'my-account-list',
  CHILD_PROFILE_LIST: 'child-profile-list',
  CHILD_ACCOUNT_LIST: 'child-account-list',
  REGULAR_LIST: 'regular-list',
  CATEGORY_REPORT: 'category-report',
  PEER_REPORT: 'peer-report',
  CHECK_REPORT_REGISTERED: 'check_report_registered',
  SUMMARY: 'summary',
  MEMO_RATE: 'memo-rate',
  REQUEST_LIST: 'request-list',
  INCREASE_REQUEST: 'increase-request',
  TRANSFER_REQUEST: 'transfer-request',
};
