services:
  nextjs:
    build:
      context: .  
      dockerfile: docker/app/Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    restart: always

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - nextjs
    volumes:
      - /etc/ssl/private/nginx_cert:/etc/nginx/ssl:ro
